name: Update Resume

on:
  schedule:
    - cron: '*/20 * * * *'  # every 20 minutes
  workflow_dispatch:      # also lets you trigger it manually

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python resume/update_resume.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git remote -v
          git add resume/pdf/resume.pdf
          git commit -m "Auto-update resume PDF" || echo "No changes to commit"
          git push origin main
